### ISSUE TITLE
论文原文获取

### ISSUE THREAD

**Issue by www-dayin** [kleinercubs/ImgFact#1]
Beyond Entities: A Large-Scale Multi-Modal Knowledge Graph with Triplet Fact Grounding
这个项目对应的论文现在网上没办法获取，可以提供原文进行学习吗？

**Comment by 15186029781** [comment]
Beyond Entities: A Large-Scale Multi-Modal Knowledge Graph with Triplet Fact Grounding
这个项目的数据集从哪儿获取啊？
Google Drive [GoogleDrive](https://drive.google.com/drive/folders/1G_QKlKSboI10ATW82Pp-1BqULxd-3TiC)这个已经不能访问了

**Comment by kleinercubs** [comment]
Sorry for the late response. README has been updated.
